backend:
  name: git-gateway
  branch: master

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "main"
    label: "Главная страница"
    files:
      - file: "content/pages/main.md"
        label: "Контент главной страницы"
        name: "main"
        fields:
          - label: "Видео"
            name: "video"
            widget: "file"
            media_folder: "/public/videos"
            public_folder: "/videos"
          - { label: "Описание", name: "description", widget: "text" }

  - name: "concerts"
    label: "Концерты"
    folder: "content/concerts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Название концерта", name: "title", widget: "string"}
      - {label: "Город", name: "city", widget: "string"}
      - {label: "Место проведения", name: "location", widget: "string"}
      - {label: "Краткое описание", name: "descriptionShort", widget: "text"}
      - {label: "Полное описание", name: "descriptionFull", widget: "text"}
      - {label: "Event ID", name: "eventId", widget: "number"}

      - label: "Дата и время"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
        picker_utc: false

      - label: "Постер"
        name: "poster"
        widget: "image"
        media_folder: "/public/images/posters"
        public_folder: "/images/posters"

      - label: "Видео"
        name: "videos"
        widget: "list"
        required: false
        field:
          label: "Видео"
          name: "video"
          widget: "file"
          media_folder: "/public/videos"
          public_folder: "/videos"

      - label: "Фотографии"
        name: "photos"
        widget: "list"
        required: false
        field:
          label: "Фото"
          name: "photo"
          widget: "image"
          media_folder: "/public/images/photos"
          public_folder: "/images/photos"

      - label: "Тип треклиста"
        name: "trackListType"
        widget: "select"
        options: ["playlist", "tracks"]
        required: false

      - label: "Ссылка на плейлист"
        name: "playlistUrl"
        widget: "string"
        required: false
        hint: "Вставьте ссылку на плейлист Яндекс.Музыки"
        condition:
          field: "trackListType"
          value: "playlist"

      - label: "Список треков"
        name: "tracks"
        widget: "list"
        required: false
        condition:
          field: "trackListType"
          value: "tracks"
        fields:
          - {label: "Музыкант", name: "musician", widget: "string"}
          - {label: "Композиция", name: "composition", widget: "string"}
          - {label: "Длительность", name: "duration", widget: "string"}